name: Install php- my first workflow
on: workflow_dispatch
jobs:
  job-install-php:
    runs-on: ubuntu-latest
    steps:
      - name: Update apt repo
        run: sudo apt update
      - name: Install php
        run: sudo apt install php -y
      - name: php version
        run: php --version
