name: Install php on ubuntu 22 and 24
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: update apt repo
        run: sudo apt update
      - name: Install php on 22
        run: sudo apt install php -y
      - name: php version
        run: php --version
  job2:
    runs-on: ubuntu-24.04
    steps:
      - name: update apt repo
        run: |
          sudo apt update
          sudo apt install php -y
          php --version
